#============================================================================#
# General configurations                                                     #
#============================================================================#

server:
    port: 8080
   
---
#============================================================================#
# Local configurations                                                       #
#============================================================================#
spring:
  datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/k8s
      username: postgres
      password: postgres