apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-post-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server-post
  template:
    metadata:
      labels:
        component: server-post
    spec:
      containers:
        - name: server-post
          image: pedrohenriquems321/k8s:1.0.3
          ports:
            - containerPort: 8080
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD